// Created by iWeb 3.0.4 local-build-20210124

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,313),url:'30_Matthias_on_the_Big_Feet_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_1.png'},{rect:new IWRect(2,-2,308,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_2.png'},{rect:new IWRect(310,-2,4,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_3.png'},{rect:new IWRect(310,2,4,313),url:'30_Matthias_on_the_Big_Feet_files/stroke_4.png'},{rect:new IWRect(310,315,4,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_5.png'},{rect:new IWRect(2,315,308,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_6.png'},{rect:new IWRect(-2,315,4,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_7.png'}],new IWSize(312,317)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,295),url:'30_Matthias_on_the_Big_Feet_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_9.png'},{rect:new IWRect(2,-2,296,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_10.png'},{rect:new IWRect(298,-2,4,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_11.png'},{rect:new IWRect(298,2,4,295),url:'30_Matthias_on_the_Big_Feet_files/stroke_12.png'},{rect:new IWRect(298,297,4,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_13.png'},{rect:new IWRect(2,297,296,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_14.png'},{rect:new IWRect(-2,297,4,4),url:'30_Matthias_on_the_Big_Feet_files/stroke_15.png'}],new IWSize(300,299))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('30_Matthias_on_the_Big_Feet_files/30_Matthias_on_the_Big_FeetMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');detectBrowser();adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
