// Created by iWeb 3.0.4 local-build-20210124

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,295),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_9.png'},{rect:new IWRect(2,-2,296,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_10.png'},{rect:new IWRect(298,-2,4,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_11.png'},{rect:new IWRect(298,2,4,295),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_12.png'},{rect:new IWRect(298,297,4,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_13.png'},{rect:new IWRect(2,297,296,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_14.png'},{rect:new IWRect(-2,297,4,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_15.png'}],new IWSize(300,299)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,309),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_1.png'},{rect:new IWRect(2,-2,306,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_2.png'},{rect:new IWRect(308,-2,5,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_3.png'},{rect:new IWRect(308,2,5,309),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_4.png'},{rect:new IWRect(308,311,5,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_5.png'},{rect:new IWRect(2,311,306,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_6.png'},{rect:new IWRect(-2,311,4,4),url:'22_Playing_around_with_Alli,_Max,_and_Gunter_files/stroke_7.png'}],new IWSize(310,313))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('22_Playing_around_with_Alli,_Max,_and_Gunter_files/22_Playing_around_with_Alli,_Max,_and_GunterMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');detectBrowser();adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
