// Created by iWeb 3.0.4 local-build-20210123

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id4" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="571" height="337" style="height: 337px; left: 45px; position: absolute; top: 588px; width: 571px; z-index: 1; "><param name="src" value="../../../../Media/VIDEO0004.mp4" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id4" type="video/quicktime" width="571" height="337" style="height: 337px; left: 45px; position: absolute; top: 588px; width: 571px; z-index: 1; "><param name="src" value="29_Thanksgiving_files/VIDEO0004.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/VIDEO0004.mp4"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id4" type="video/quicktime" width="571" height="337" data="../../../../Media/VIDEO0004.mp4" style="height: 337px; left: 45px; position: absolute; top: 588px; width: 571px; z-index: 1; "><param name="src" value="../../../../Media/VIDEO0004.mp4"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,250),url:'29_Thanksgiving_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'29_Thanksgiving_files/stroke_1.png'},{rect:new IWRect(1,-1,246,2),url:'29_Thanksgiving_files/stroke_2.png'},{rect:new IWRect(247,-1,2,2),url:'29_Thanksgiving_files/stroke_3.png'},{rect:new IWRect(247,1,2,250),url:'29_Thanksgiving_files/stroke_4.png'},{rect:new IWRect(247,251,2,2),url:'29_Thanksgiving_files/stroke_5.png'},{rect:new IWRect(1,251,246,2),url:'29_Thanksgiving_files/stroke_6.png'},{rect:new IWRect(-1,251,2,2),url:'29_Thanksgiving_files/stroke_7.png'}],new IWSize(248,252)),shadow_2:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_5:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_4:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_1:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_3:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('29_Thanksgiving_files/29_ThanksgivingMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');Widget.onload();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
