// Created by iWeb 3.0.4 local-build-20210124

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,295),url:'5_Max_Race_+_Exploring_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'5_Max_Race_+_Exploring_files/stroke_9.png'},{rect:new IWRect(2,-2,296,4),url:'5_Max_Race_+_Exploring_files/stroke_10.png'},{rect:new IWRect(298,-2,4,4),url:'5_Max_Race_+_Exploring_files/stroke_11.png'},{rect:new IWRect(298,2,4,295),url:'5_Max_Race_+_Exploring_files/stroke_12.png'},{rect:new IWRect(298,297,4,4),url:'5_Max_Race_+_Exploring_files/stroke_13.png'},{rect:new IWRect(2,297,296,4),url:'5_Max_Race_+_Exploring_files/stroke_14.png'},{rect:new IWRect(-2,297,4,4),url:'5_Max_Race_+_Exploring_files/stroke_15.png'}],new IWSize(300,299)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,289),url:'5_Max_Race_+_Exploring_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'5_Max_Race_+_Exploring_files/stroke_1.png'},{rect:new IWRect(2,-2,294,4),url:'5_Max_Race_+_Exploring_files/stroke_2.png'},{rect:new IWRect(296,-2,5,4),url:'5_Max_Race_+_Exploring_files/stroke_3.png'},{rect:new IWRect(296,2,5,289),url:'5_Max_Race_+_Exploring_files/stroke_4.png'},{rect:new IWRect(296,291,5,4),url:'5_Max_Race_+_Exploring_files/stroke_5.png'},{rect:new IWRect(2,291,294,4),url:'5_Max_Race_+_Exploring_files/stroke_6.png'},{rect:new IWRect(-2,291,4,4),url:'5_Max_Race_+_Exploring_files/stroke_7.png'}],new IWSize(298,293))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('5_Max_Race_+_Exploring_files/5_Max_Race_+_ExploringMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');detectBrowser();adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
